import { Injectable } from '@angular/core';
import { Product } from '../models/product.model';
//import { Product } from '../models/product.model';


@Injectable({
  providedIn: 'root',
})
export class ProductService {
  private products: Product[] = [
    {
      id: 1,
      brand: 'BMW',
      model: 'X5',
      price: 75000,
      releaseDate: new Date(2023, 4, 12),
      bodyType: 'SUV',
      engine: '3.0L Turbo Inline-6',
      fuelType: 'Petrol',
      transmission: 'Automatic',
      color: 'Black',
      imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/1/1b/2019_BMW_X5_M50d_Automatic_3.0.jpg',
      wikiUrl: 'https://en.wikipedia.org/wiki/BMW_X5',
      officialUrl: 'https://www.bmw.in/en/all-models/x-series/X5/2023/bmw-x5-overview.html'
    },
    {
      id: 2,
      brand: 'Mercedes-Benz',
      model: 'C-Class',
      price: 65000,
      releaseDate: new Date(2022, 10, 20),
      bodyType: 'Sedan',
      engine: '2.0L Turbo',
      fuelType: 'Diesel',
      transmission: 'Automatic',
      color: 'White',
      imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/1/12/2021_Mercedes-Benz_C_200_Avantgarde_Line.jpg',
      wikiUrl: 'https://en.wikipedia.org/wiki/Mercedes-Benz_C-Class',
      officialUrl: 'https://www.mercedes-benz.com/en/vehicles/passenger-cars/c-class/'
    },
    {
      id: 3,
      brand: 'Tata',
      model: 'Nexon EV',
      price: 19000,
      releaseDate: new Date(2023, 7, 1),
      bodyType: 'SUV',
      engine: 'Electric Motor',
      fuelType: 'Electric',
      transmission: 'Automatic',
      color: 'Blue',
      imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/3/36/Tata_Nexon_EV.jpg',
      wikiUrl: 'https://en.wikipedia.org/wiki/Tata_Nexon',
      officialUrl: 'https://nexonev.tatamotors.com/'
    },
    {
      id: 4,
      brand: 'Hyundai',
      model: 'i20',
      price: 10000,
      releaseDate: new Date(2023, 1, 18),
      bodyType: 'Hatchback',
      engine: '1.2L Petrol',
      fuelType: 'Petrol',
      transmission: 'Manual',
      color: 'Red',
      imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/e/e7/2020_Hyundai_i20.jpg',
      wikiUrl: 'https://en.wikipedia.org/wiki/Hyundai_i20',
      officialUrl: 'https://www.hyundai.com/in/en/find-a-car/i20/highlights.html'
    },
    {
      id: 5,
      brand: 'Maruti Suzuki',
      model: 'Baleno',
      price: 9500,
      releaseDate: new Date(2022, 3, 15),
      bodyType: 'Hatchback',
      engine: '1.2L VVT',
      fuelType: 'Petrol',
      transmission: 'Manual',
      color: 'Grey',
      imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/a/a5/Maruti_Baleno.jpg',
      wikiUrl: 'https://en.wikipedia.org/wiki/Suzuki_Baleno',
      officialUrl: 'https://www.nexaexperience.com/baleno'
    },
    {
      id: 6,
      brand: 'Audi',
      model: 'A4',
      price: 55000,
      releaseDate: new Date(2023, 2, 28),
      bodyType: 'Sedan',
      engine: '2.0L TFSI',
      fuelType: 'Petrol',
      transmission: 'Automatic',
      color: 'Silver',
      imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/f/fc/Audi_A4_B9.jpg',
      wikiUrl: 'https://en.wikipedia.org/wiki/Audi_A4',
      officialUrl: 'https://www.audi.in/in/web/en/models/a4/a4-sedan.html'
    },
    {
      id: 7,
      brand: 'Kia',
      model: 'Seltos',
      price: 17000,
      releaseDate: new Date(2022, 11, 5),
      bodyType: 'SUV',
      engine: '1.5L CRDi',
      fuelType: 'Diesel',
      transmission: 'Manual',
      color: 'Blue',
      imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/8/8e/Kia_Seltos.jpg',
      wikiUrl: 'https://en.wikipedia.org/wiki/Kia_Seltos',
      officialUrl: 'https://www.kia.com/in/seltos.html'
    },
    {
      id: 8,
      brand: 'Volkswagen',
      model: 'Virtus',
      price: 16000,
      releaseDate: new Date(2023, 5, 25),
      bodyType: 'Sedan',
      engine: '1.0L TSI',
      fuelType: 'Petrol',
      transmission: 'Manual',
      color: 'Red',
      imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/2/2b/Volkswagen_Virtus_GT.jpg',
      wikiUrl: 'https://en.wikipedia.org/wiki/Volkswagen_Virtus',
      officialUrl: 'https://www.volkswagen.co.in/en/models/virtus.html'
    },
    {
      id: 9,
      brand: 'Mahindra',
      model: 'XUV700',
      price: 22000,
      releaseDate: new Date(2023, 3, 10),
      bodyType: 'SUV',
      engine: '2.2L mHawk Diesel',
      fuelType: 'Diesel',
      transmission: 'Automatic',
      color: 'Black',
      imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/5/56/Mahindra_XUV700.jpg',
      wikiUrl: 'https://en.wikipedia.org/wiki/Mahindra_XUV700',
      officialUrl: 'https://auto.mahindra.com/suvs/xuv700'
    },
    {
      id: 10,
      brand: 'Honda',
      model: 'City',
      price: 15000,
      releaseDate: new Date(2023, 6, 8),
      bodyType: 'Sedan',
      engine: '1.5L i-VTEC',
      fuelType: 'Petrol',
      transmission: 'Manual',
      color: 'White',
      imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/b/b9/2020_Honda_City.jpg',
      wikiUrl: 'https://en.wikipedia.org/wiki/Honda_City',
      officialUrl: 'https://www.hondacarindia.com/honda-city'
    },
    // You can continue adding for cars 11–20 similarly if you want — just let me know!
    {
      id: 11,
      brand: 'Skoda',
      model: 'Kushaq',
      price: 18000,
      releaseDate: new Date(2022, 7, 14),
      bodyType: 'SUV',
      engine: '1.0L TSI',
      fuelType: 'Petrol',
      transmission: 'Manual',
      color: 'Orange',
      imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/d/d4/Skoda_Kushaq_1.0_TSI.jpg',
      wikiUrl: 'https://en.wikipedia.org/wiki/Škoda_Kushaq',
      officialUrl: 'https://www.skoda-auto.com/models/kushaq'
    },
    {
      id: 12,
      brand: 'MG',
      model: 'Hector',
      price: 20000,
      releaseDate: new Date(2023, 8, 19),
      bodyType: 'SUV',
      engine: '1.5L Turbo Petrol',
      fuelType: 'Petrol',
      transmission: 'Automatic',
      color: 'Grey',
      imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/d/d2/MG_Hector.jpg',
      wikiUrl: 'https://en.wikipedia.org/wiki/MG_Hector',
      officialUrl: 'https://www.mgmotor.co.in/hector'
    },
    {
      id: 13,
      brand: 'Toyota',
      model: 'Innova HyCross',
      price: 30000,
      releaseDate: new Date(2023, 9, 22),
      bodyType: 'SUV',
      engine: '2.0L Hybrid',
      fuelType: 'Hybrid',
      transmission: 'Automatic',
      color: 'Silver',
      imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/3/36/Toyota_Innova_HyCross.jpg',
      wikiUrl: 'https://en.wikipedia.org/wiki/Toyota_Innova',
      officialUrl: 'https://www.toyotabharat.com/showroom/innova-hycross'
    },
    {
      id: 14,
      brand: 'Ford',
      model: 'EcoSport',
      price: 16000,
      releaseDate: new Date(2021, 11, 4),
      bodyType: 'SUV',
      engine: '1.5L Petrol',
      fuelType: 'Petrol',
      transmission: 'Manual',
      color: 'Blue',
      imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/9/90/2018_Ford_EcoSport.jpg',
      wikiUrl: 'https://en.wikipedia.org/wiki/Ford_EcoSport',
      officialUrl: 'https://www.ford.com/suvs/ecosport/'
    },
    {
      id: 15,
      brand: 'Nissan',
      model: 'Magnite',
      price: 13000,
      releaseDate: new Date(2022, 10, 30),
      bodyType: 'SUV',
      engine: '1.0L Turbo',
      fuelType: 'Petrol',
      transmission: 'Manual',
      color: 'White',
      imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/4/47/Nissan_Magnite.jpg',
      wikiUrl: 'https://en.wikipedia.org/wiki/Nissan_Magnite',
      officialUrl: 'https://www.nissan.in/vehicles/new/magnite.html'
    },
    {
      id: 16,
      brand: 'Renault',
      model: 'Kiger',
      price: 12000,
      releaseDate: new Date(2023, 1, 5),
      bodyType: 'SUV',
      engine: '1.0L Turbo',
      fuelType: 'Petrol',
      transmission: 'Manual',
      color: 'Silver',
      imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/a/a6/Renault_Kiger.jpg',
      wikiUrl: 'https://en.wikipedia.org/wiki/Renault_Kiger',
      officialUrl: 'https://www.renault.co.in/cars/kiger.html'
    },
    {
      id: 17,
      brand: 'Tesla',
      model: 'Model 3',
      price: 48000,
      releaseDate: new Date(2023, 2, 11),
      bodyType: 'Sedan',
      engine: 'Dual Motor Electric',
      fuelType: 'Electric',
      transmission: 'Automatic',
      color: 'White',
      imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/1/1e/Tesla_Model_3_parked%2C_front_driver_side.jpg',
      wikiUrl: 'https://en.wikipedia.org/wiki/Tesla_Model_3',
      officialUrl: 'https://www.tesla.com/model3'
    },
    {
      id: 18,
      brand: 'Jeep',
      model: 'Compass',
      price: 28000,
      releaseDate: new Date(2023, 3, 7),
      bodyType: 'SUV',
      engine: '2.0L Diesel',
      fuelType: 'Diesel',
      transmission: 'Manual',
      color: 'Red',
      imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/b/bb/Jeep_Compass.jpg',
      wikiUrl: 'https://en.wikipedia.org/wiki/Jeep_Compass',
      officialUrl: 'https://www.jeep-india.com/compass.html'
    },
    {
      id: 19,
      brand: 'Maruti Suzuki',
      model: 'Swift',
      price: 9000,
      releaseDate: new Date(2023, 4, 16),
      bodyType: 'Hatchback',
      engine: '1.2L DualJet',
      fuelType: 'Petrol',
      transmission: 'Manual',
      color: 'Grey',
      imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/d/d3/Maruti_Suzuki_Swift.jpg',
      wikiUrl: 'https://en.wikipedia.org/wiki/Suzuki_Swift',
      officialUrl: 'https://www.marutisuzuki.com/swift'
    },
    {
      id: 20,
      brand: 'Honda',
      model: 'Amaze',
      price: 12000,
      releaseDate: new Date(2022, 12, 12),
      bodyType: 'Sedan',
      engine: '1.2L i-VTEC',
      fuelType: 'Petrol',
      transmission: 'Automatic',
      color: 'Black',
      imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/4/4d/Honda_Amaze.jpg',
      wikiUrl: 'https://en.wikipedia.org/wiki/Honda_Amaze',
      officialUrl: 'https://www.hondacarindia.com/amaze'
    }
  ];



  getProducts(): Product[] {
    return this.products;
  }
}
