import { Injectable } from '@angular/core';
import { Product } from '../models/product.model';


@Injectable({
  providedIn: 'root',
})
export class ProductService {
  private products: Product[] =

  [
    {
      id: 1,
      brand: 'Maruti Suzuki',
      model: 'Swift',
      price: 600000,
      releaseDate: new Date(2023, 4, 1),
      bodyType: 'Hatchback',
      engine: '1.2L Dualjet Petrol',
      fuelType: 'Petrol',
      transmission: 'Manual/AMT',
      color: 'Fire Red',
      imageUrl: 'Maruti Suzuki Swift_.jpeg',
      wikiUrl: 'https://en.wikipedia.org/wiki/Maruti_Suzuki_Swift',
      officialUrl: 'https://www.marutisuzuki.com/swift'
    },
    {
      id: 2,
      brand: 'Hyundai',
      model: 'i20',
      price: 720000,
      releaseDate: new Date(2023, 5, 10),
      bodyType: 'Hatchback',
      engine: '1.2L Kappa Petrol',
      fuelType: 'Petrol',
      transmission: 'Manual/CVT',
      color: 'Titan Grey',
      imageUrl: 'Hyundai i20.jpeg',
      wikiUrl: 'https://en.wikipedia.org/wiki/Hyundai_i20',
      officialUrl: 'https://www.hyundai.com/in/en/find-a-car/i20/highlights.html'
    },
    {
      id: 3,
      brand: 'Tata',
      model: 'Tiago',
      price: 550000,
      releaseDate: new Date(2023, 1, 1),
      bodyType: 'Hatchback',
      engine: '1.2L Revotron Petrol',
      fuelType: 'Petrol',
      transmission: 'Manual/Automatic',
      color: 'Flame Red',
      imageUrl: 'Tata Tiago.jpeg',
      wikiUrl: 'https://en.wikipedia.org/wiki/Tata_Tiago',
      officialUrl: 'https://cars.tatamotors.com/cars/tiago'
    },
    {
      id: 4,
      brand: 'Maruti Suzuki',
      model: 'Baleno',
      price: 730000,
      releaseDate: new Date(2022, 1, 23),
      bodyType: 'Hatchback',
      engine: '1.2L Dualjet Petrol',
      fuelType: 'Petrol',
      transmission: 'Manual/AMT',
      color: 'Nexa Blue',
      imageUrl: 'Maruti Suzuki Baleno.webp',
      wikiUrl: 'https://en.wikipedia.org/wiki/Maruti_Suzuki_Baleno',
      officialUrl: 'https://www.nexaexperience.com/baleno'
    },
    {
      id: 5,
      brand: 'Tata',
      model: 'Altroz',
      price: 660000,
      releaseDate: new Date(2023, 0, 10),
      bodyType: 'Hatchback',
      engine: '1.2L Revotron Petrol',
      fuelType: 'Petrol',
      transmission: 'Manual/Automatic',
      color: 'High Street Gold',
      imageUrl: 'Tata Altroz.webp',
      wikiUrl: 'https://en.wikipedia.org/wiki/Tata_Altroz',
      officialUrl: 'https://cars.tatamotors.com/cars/altroz'
    },
    {
      id: 6,
      brand: 'Hyundai',
      model: 'Grand i10 Nios',
      price: 590000,
      releaseDate: new Date(2023, 2, 15),
      bodyType: 'Hatchback',
      engine: '1.2L Kappa Petrol',
      fuelType: 'Petrol',
      transmission: 'Manual/AMT',
      color: 'Aqua Teal',
      imageUrl: 'Hyundai Grand i10 Nios.webp',
      wikiUrl: 'https://en.wikipedia.org/wiki/Hyundai_i10#Grand_i10_Nios_(AI3;_2019)',
      officialUrl: 'https://www.hyundai.com/in/en/find-a-car/grand-i10-nios/highlights.html'
    },
    {
      id: 7,
      brand: 'Ford',
      model: 'Figo',
      price: 620000,
      releaseDate: new Date(2019, 5, 1),
      bodyType: 'Hatchback',
      engine: '1.2L Ti-VCT Petrol',
      fuelType: 'Petrol',
      transmission: 'Manual',
      color: 'Moondust Silver',
      imageUrl: 'Ford Figo.webp',
      wikiUrl: 'https://en.wikipedia.org/wiki/Ford_Figo',
      officialUrl: 'https://www.india.ford.com/cars/figo/'
    },
    {
      id: 8,
      brand: 'Chevrolet',
      model: 'Beat',
      price: 500000,
      releaseDate: new Date(2017, 4, 1),
      bodyType: 'Hatchback',
      engine: '1.0L Petrol/Diesel',
      fuelType: 'Petrol/Diesel',
      transmission: 'Manual',
      color: 'Linen Beige',
      imageUrl: 'Chevrolet Beat.webp',
      wikiUrl: 'https://en.wikipedia.org/wiki/Chevrolet_Spark#Chevrolet_Beat',
      officialUrl: 'https://www.chevrolet.co.in/beat.html'
    },
    {
      id: 9,
      brand: 'Volkswagen',
      model: 'Golf',
      price: 1600000,
      releaseDate: new Date(2020, 0, 1),
      bodyType: 'Hatchback',
      engine: '1.5L TSI Petrol',
      fuelType: 'Petrol',
      transmission: 'Manual/DSG',
      color: 'Lime Yellow',
      imageUrl: 'https://imgd.aeplcdn.com/310x174/n/cw/ec/38913/golf-exterior-right-front-three-quarter.jpeg',
      wikiUrl: 'https://en.wikipedia.org/wiki/Volkswagen_Golf',
      officialUrl: 'https://www.volkswagen.co.uk/en/models-and-configurator/golf.html'
    },
    {
      id: 10,
      brand: 'Honda',
      model: 'City',
      price: 1200000,
      releaseDate: new Date(2023, 6, 1),
      bodyType: 'Sedan',
      engine: '1.5L i-VTEC / 1.5L e:HEV Hybrid',
      fuelType: 'Petrol/Hybrid',
      transmission: 'Manual/CVT/eCVT',
      color: 'Radiant Red',
      imageUrl: 'https://imgd.aeplcdn.com/310x174/n/cw/ec/141799/city-exterior-right-front-three-quarter.jpeg',
      wikiUrl: 'https://en.wikipedia.org/wiki/Honda_City',
      officialUrl: 'https://www.hondacarindia.com/honda-city'
    },
    {
      id: 11,
      brand: 'Hyundai',
      model: 'Verna',
      price: 1150000,
      releaseDate: new Date(2023, 2, 21),
      bodyType: 'Sedan',
      engine: '1.5L MPi / 1.5L Turbo GDi',
      fuelType: 'Petrol',
      transmission: 'Manual/CVT/DCT',
      color: 'Fiery Red',
      imageUrl: 'https://imgd.aeplcdn.com/310x174/n/cw/ec/144419/verna-exterior-right-front-three-quarter.jpeg',
      wikiUrl: 'https://en.wikipedia.org/wiki/Hyundai_Verna',
      officialUrl: 'https://www.hyundai.com/in/en/find-a-car/verna/highlights.html'
    },
    {
      id: 12,
      brand: 'Maruti Suzuki',
      model: 'Dzire',
      price: 700000,
      releaseDate: new Date(2022, 0, 15),
      bodyType: 'Sedan',
      engine: '1.2L Dualjet Petrol',
      fuelType: 'Petrol',
      transmission: 'Manual/AMT',
      color: 'Oxford Blue',
      imageUrl: 'https://imgd.aeplcdn.com/310x174/n/cw/ec/103243/dzire-exterior-right-front-three-quarter.jpeg',
      wikiUrl: 'https://en.wikipedia.org/wiki/Maruti_Suzuki_Dzire',
      officialUrl: 'https://www.marutisuzuki.com/dzire'
    },
    {
      id: 13,
      brand: 'Skoda',
      model: 'Slavia',
      price: 1100000,
      releaseDate: new Date(2022, 1, 28),
      bodyType: 'Sedan',
      engine: '1.0L / 1.5L TSI Petrol',
      fuelType: 'Petrol',
      transmission: 'Manual/DSG',
      color: 'Crystal Blue',
      imageUrl: 'https://imgd.aeplcdn.com/310x174/n/cw/ec/132423/slavia-exterior-right-front-three-quarter.jpeg',
      wikiUrl: 'https://en.wikipedia.org/wiki/Škoda_Slavia',
      officialUrl: 'https://www.skoda-auto.co.in/models/slavia/slavia'
    },
    {
      id: 14,
      brand: 'Volkswagen',
      model: 'Virtus',
      price: 1150000,
      releaseDate: new Date(2022, 5, 9),
      bodyType: 'Sedan',
      engine: '1.0L / 1.5L TSI Petrol',
      fuelType: 'Petrol',
      transmission: 'Manual/DSG',
      color: 'Wild Cherry Red',
      imageUrl: 'https://imgd.aeplcdn.com/310x174/n/cw/ec/134227/virtus-exterior-right-front-three-quarter.jpeg',
      wikiUrl: 'https://en.wikipedia.org/wiki/Volkswagen_Virtus',
      officialUrl: 'https://www.volkswagen.co.in/en/models/virtus.html'
    },
    {
      id: 15,
      brand: 'Toyota',
      model: 'Camry',
      price: 4600000,
      releaseDate: new Date(2023, 0, 1),
      bodyType: 'Sedan',
      engine: '2.5L Petrol Hybrid',
      fuelType: 'Hybrid',
      transmission: 'eCVT',
      color: 'Graphite Metallic',
      imageUrl: 'https://imgd.aeplcdn.com/310x174/n/cw/ec/104881/camry-exterior-right-front-three-quarter.jpeg',
      wikiUrl: 'https://en.wikipedia.org/wiki/Toyota_Camry',
      officialUrl: 'https://www.toyotabharat.com/showroom/camry/'
    },
    {
      id: 16,
      brand: 'Honda',
      model: 'Amaze',
      price: 720000,
      releaseDate: new Date(2023, 7, 1),
      bodyType: 'Sedan',
      engine: '1.2L i-VTEC Petrol',
      fuelType: 'Petrol',
      transmission: 'Manual/CVT',
      color: 'Platinum White Pearl',
      imageUrl: 'https://imgd.aeplcdn.com/310x174/n/cw/ec/144189/amaze-exterior-right-front-three-quarter.jpeg',
      wikiUrl: 'https://en.wikipedia.org/wiki/Honda_Amaze',
      officialUrl: 'https://www.hondacarindia.com/honda-amaze'
    },
    {
      id: 17,
      brand: 'Volkswagen',
      model: 'Vento',
      price: 950000,
      releaseDate: new Date(2019, 2, 1),
      bodyType: 'Sedan',
      engine: '1.0L TSI Petrol',
      fuelType: 'Petrol',
      transmission: 'Manual/Automatic',
      color: 'Carbon Steel',
      imageUrl: 'https://imgd.aeplcdn.com/310x174/n/cw/ec/35753/vento-exterior-right-front-three-quarter.jpeg',
      wikiUrl: 'https://en.wikipedia.org/wiki/Volkswagen_Vento_(A05)',
      officialUrl: 'https://www.volkswagen.co.in/en/models/vento.html'
    },
    {
      id: 18,
      brand: 'Ford',
      model: 'Aspire',
      price: 800000,
      releaseDate: new Date(2018, 9, 1),
      bodyType: 'Sedan',
      engine: '1.2L Ti-VCT Petrol',
      fuelType: 'Petrol',
      transmission: 'Manual',
      color: 'Ruby Red',
      imageUrl: 'https://imgd.aeplcdn.com/310x174/n/cw/ec/46355/aspire-exterior-right-front-three-quarter.jpeg',
      wikiUrl: 'https://en.wikipedia.org/wiki/Ford_Figo_Aspire',
      officialUrl: 'https://www.india.ford.com/cars/aspire/'
    },
    {
      id: 19,
      brand: 'Citroen',
      model: 'C3X',
      price: 1000000,
      releaseDate: new Date(2025, 0, 1),
      bodyType: 'Sedan',
      engine: '1.2L Turbo Petrol',
      fuelType: 'Petrol',
      transmission: 'Manual/Automatic',
      color: 'Zesty Orange',
      imageUrl: 'https://imgd.aeplcdn.com/310x174/n/cw/ec/144959/c3x-exterior-right-front-three-quarter.jpeg',
      wikiUrl: 'https://en.wikipedia.org/wiki/Citroën_C3_(CC21)',
      officialUrl: 'https://www.citroen.in'
    },
    {
      id: 20,
      brand: 'Honda',
      model: 'City (5th Gen)',
      price: 1238000,
      releaseDate: new Date(2020, 6, 15),
      bodyType: 'Sedan',
      engine: '1.5L i-VTEC / 1.5L e:HEV',
      fuelType: 'Petrol / Hybrid',
      transmission: 'Manual',
      color: 'Radiant Red Metallic',
      imageUrl: 'https://imgd.aeplcdn.com/310x174/n/cw/ec/130591/city-exterior-right-front-three-quarter-2.jpeg',
      wikiUrl: 'https://en.wikipedia.org/wiki/Honda_City',
      officialUrl: 'https://www.hondacarindia.com/honda-city-5th-generation'
    },
    {
      id: 21,
      brand: 'Hyundai',
      model: 'Verna (2023)',
      price: 1089000,
      releaseDate: new Date(2023, 2, 21),
      bodyType: 'Sedan',
      engine: '1.5L MPi / 1.5L Turbo GDi',
      fuelType: 'Petrol',
      transmission: 'Manual / CVT / DCT',
      color: 'Fiery Red',
      imageUrl: 'https://imgd.aeplcdn.com/310x174/n/cw/ec/130591/verna-exterior-right-front-three-quarter-3.jpeg',
      wikiUrl: 'https://en.wikipedia.org/wiki/Hyundai_Verna',
      officialUrl: 'https://www.hyundai.com/in/en/find-a-car/verna/highlights'
    },
    {
      id: 22,
      brand: 'Maruti Suzuki',
      model: 'Dzire',
      price: 684000,
      releaseDate: new Date(2024, 10, 11),
      bodyType: 'Sedan',
      engine: '1.2L DualJet Petrol',
      fuelType: 'Petrol / CNG',
      transmission: 'Manual / AMT',
      color: 'Oxford Blue',
      imageUrl: 'https://imgd.aeplcdn.com/310x174/n/cw/ec/130591/dzire-exterior-right-front-three-quarter-2.jpeg',
      wikiUrl: 'https://en.wikipedia.org/wiki/Maruti_Suzuki_Dzire',
      officialUrl: 'https://www.marutisuzuki.com/dzire'
    },
    {
      id: 23,
      brand: 'Skoda',
      model: 'Slavia',
      price: 1034000,
      releaseDate: new Date(2022, 2, 1),
      bodyType: 'Sedan',
      engine: '1.0L TSI / 1.5L TSI',
      fuelType: 'Petrol',
      transmission: 'Manual / Automatic',
      color: 'Crystal Blue',
      imageUrl: 'https://imgd.aeplcdn.com/310x174/n/cw/ec/130591/slavia-exterior-right-front-three-quarter-2.jpeg',
      wikiUrl: 'https://en.wikipedia.org/wiki/Škoda_Slavia',
      officialUrl: 'https://www.skoda-auto.co.in/models/slavia/slavia'
    },
    {
      id: 24,
      brand: 'Volkswagen',
      model: 'Virtus',
      price: 1121000,
      releaseDate: new Date(2022, 5, 9),
      bodyType: 'Sedan',
      engine: '1.0L TSI / 1.5L TSI',
      fuelType: 'Petrol',
      transmission: 'Manual / Automatic',
      color: 'Carbon Steel Grey',
      imageUrl: 'https://imgd.aeplcdn.com/310x174/n/cw/ec/130591/virtus-exterior-right-front-three-quarter-3.jpeg',
      wikiUrl: 'https://en.wikipedia.org/wiki/Volkswagen_Virtus',
      officialUrl: 'https://www.volkswagen.co.in/en/models/virtus.html'
    },
    {
      id: 25,
      brand: 'Toyota',
      model: 'Camry Hybrid',
      price: 4800000,
      releaseDate: new Date(2024, 11, 11),
      bodyType: 'Sedan',
      engine: '2.5L Hybrid',
      fuelType: 'Petrol / Hybrid',
      transmission: 'e-CVT',
      color: 'Attitude Black',
      imageUrl: 'https://imgd.aeplcdn.com/310x174/n/cw/ec/130591/camry-exterior-right-front-three-quarter-2.jpeg',
      wikiUrl: 'https://en.wikipedia.org/wiki/Toyota_Camry',
      officialUrl: 'https://www.toyotabharat.com/showroom/camry/'
    },
    {
      id: 26,
      brand: 'Honda',
      model: 'Amaze',
      price: 814000,
      releaseDate: new Date(2024, 11, 4),
      bodyType: 'Sedan',
      engine: '1.2L i-VTEC',
      fuelType: 'Petrol',
      transmission: 'Manual / CVT',
      color: 'Platinum White Pearl',
      imageUrl: 'https://imgd.aeplcdn.com/310x174/n/cw/ec/130591/amaze-exterior-right-front-three-quarter-2.jpeg',
      wikiUrl: 'https://en.wikipedia.org/wiki/Honda_Amaze',
      officialUrl: 'https://www.hondacarindia.com/honda-amaze'
    },
    {
      id: 27,
      brand: 'Volkswagen',
      model: 'Vento',
      price: 1400000,
      releaseDate: new Date(2010, 8, 6),
      bodyType: 'Sedan',
      engine: '1.0L TSI / 1.5L TDI',
      fuelType: 'Petrol / Diesel',
      transmission: 'Manual / Automatic',
      color: 'Reflex Silver',
      imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/9/9a/2019_Volkswagen_Vento_1.0_TSI_SE_%28Facelift%29_1.5L.jpg',
      wikiUrl: 'https://en.wikipedia.org/wiki/Volkswagen_Vento_(A05)',
      officialUrl: 'https://en.wikipedia.org/wiki/Volkswagen_Vento_(A05)',
      // status: 'Discontinued (2022)'
    },
    {
      id: 28,
      brand: 'Ford',
      model: 'Aspire',
      price: 1300000,
      releaseDate: new Date(2015, 7, 12),
      bodyType: 'Sedan',
      engine: '1.2L Ti-VCT / 1.5L TDCi',
      fuelType: 'Petrol / Diesel',
      transmission: 'Manual / Automatic',
      color: 'Moondust Silver',
      imageUrl: 'https://imgd.aeplcdn.com/310x174/n/cw/ec/130591/aspire-exterior-right-front-three-quarter-2.jpeg',
      wikiUrl: 'https://en.wikipedia.org/wiki/Ford_Figo_Aspire',
      officialUrl: 'https://en.wikipedia.org/wiki/Ford_Figo_Aspire',
      // status: 'Discontinued (2021)'
    },
    {
      id: 29,
      brand: 'Citroen',
      model: 'C3X',
      price: 1200000,
      releaseDate: new Date(2026, 6, 1),
      bodyType: 'Sedan',
      engine: 'TBD',
      fuelType: 'Petrol / Electric (Expected)',
      transmission: 'TBD',
      color: 'TBD',
      imageUrl: 'https://www.cardekho.com/india-car-news/heres-your-first-unofficial-look-at-the-citroen-c3x-crossover-sedans-interior-31874.htm',
      wikiUrl: 'https://www.cardekho.com/india-car-news/heres-your-first-unofficial-look-at-the-citroen-c3x-crossover-sedans-interior-31874.htm',
      officialUrl: 'https://www.cardekho.com/india-car-news/heres-your-first-unofficial-look-at-the-citroen-c3x-crossover-sedans-interior-31874.htm',
      // status: 'Upcoming'
    },
    {
      id: 30,
      brand: 'Tata',
      model: 'Nexon',
      price: 879000,
      releaseDate: new Date(2023, 8, 14),
      bodyType: 'Compact SUV',
      engine: '1.2L Turbo Petrol / 1.5L Diesel',
      fuelType: 'Petrol / Diesel / EV',
      transmission: 'Manual / AMT / DCT',
      color: 'Fearless Purple',
      imageUrl: 'https://imgd.aeplcdn.com/310x174/n/cw/ec/145965/nexon-exterior-right-front-three-quarter-3.jpeg',
      wikiUrl: 'https://en.wikipedia.org/wiki/Tata_Nexon',
      officialUrl: 'https://cars.tatamotors.com/suv/nexon'
    },
    {
      id: 31,
      brand: 'Maruti Suzuki',
      model: 'Brezza',
      price: 834000,
      releaseDate: new Date(2022, 5, 30),
      bodyType: 'Compact SUV',
      engine: '1.5L K-Series',
      fuelType: 'Petrol / CNG',
      transmission: 'Manual / Automatic',
      color: 'Exuberant Blue',
      imageUrl: 'https://imgd.aeplcdn.com/310x174/n/cw/ec/111197/brezza-exterior-right-front-three-quarter.jpeg',
      wikiUrl: 'https://en.wikipedia.org/wiki/Maruti_Suzuki_Brezza',
      officialUrl: 'https://www.marutisuzuki.com/arena/brezza'
    },
    {
      id: 32,
      brand: 'Hyundai',
      model: 'Venue',
      price: 781000,
      releaseDate: new Date(2022, 5, 16),
      bodyType: 'Compact SUV',
      engine: '1.2L MPi / 1.0L Turbo / 1.5L Diesel',
      fuelType: 'Petrol / Diesel',
      transmission: 'Manual / iMT / DCT',
      color: 'Fiery Red with Black Roof',
      imageUrl: 'https://imgd.aeplcdn.com/310x174/n/cw/ec/110183/venue-exterior-right-front-three-quarter-2.jpeg',
      wikiUrl: 'https://en.wikipedia.org/wiki/Hyundai_Venue',
      officialUrl: 'https://www.hyundai.com/in/en/find-a-car/venue/highlights'
    },
    {
      id: 33,
      brand: 'Kia',
      model: 'Sonet',
      price: 799000,
      releaseDate: new Date(2023, 11, 14),
      bodyType: 'Compact SUV',
      engine: '1.2L Petrol / 1.0L Turbo / 1.5L Diesel',
      fuelType: 'Petrol / Diesel',
      transmission: 'Manual / iMT / DCT / Automatic',
      color: 'Intense Red',
      imageUrl: 'https://imgd.aeplcdn.com/310x174/n/cw/ec/145739/sonet-exterior-right-front-three-quarter-2.jpeg',
      wikiUrl: 'https://en.wikipedia.org/wiki/Kia_Sonet',
      officialUrl: 'https://www.kia.com/in/our-vehicles/sonet/showroom.html'
    },
    {
      id: 34,
      brand: 'Nissan',
      model: 'Magnite',
      price: 599000,
      releaseDate: new Date(2020, 11, 2),
      bodyType: 'Compact SUV',
      engine: '1.0L NA / 1.0L Turbo',
      fuelType: 'Petrol',
      transmission: 'Manual / AMT / CVT',
      color: 'Tourmaline Brown with Onyx Black Roof',
      imageUrl: 'https://imgd.aeplcdn.com/310x174/n/cw/ec/146271/magnite-exterior-right-front-three-quarter-3.jpeg',
      wikiUrl: 'https://en.wikipedia.org/wiki/Nissan_Magnite',
      officialUrl: 'https://www.nissan.in/vehicles/new/magnite.html'
    },
    {
      id: 35,
      brand: 'Renault',
      model: 'Kiger',
      price: 649000,
      releaseDate: new Date(2021, 1, 15),
      bodyType: 'Compact SUV',
      engine: '1.0L NA / 1.0L Turbo',
      fuelType: 'Petrol',
      transmission: 'Manual / AMT / CVT',
      color: 'Caspian Blue',
      imageUrl: 'https://imgd.aeplcdn.com/310x174/n/cw/ec/146259/kiger-exterior-right-front-three-quarter-3.jpeg',
      wikiUrl: 'https://en.wikipedia.org/wiki/Renault_Kiger',
      officialUrl: 'https://www.renault.co.in/cars/kiger.html'
    },
    {
      id: 36,
      brand: 'Ford',
      model: 'EcoSport',
      price: 869000,
      releaseDate: new Date(2013, 5, 26),
      bodyType: 'Compact SUV',
      engine: '1.5L Ti-VCT / 1.0L EcoBoost',
      fuelType: 'Petrol / Diesel',
      transmission: 'Manual / Automatic',
      color: 'Smoke Grey',
      imageUrl: 'https://imgd.aeplcdn.com/310x174/n/cw/ec/126341/ecosport-exterior-right-front-three-quarter.jpeg',
      wikiUrl: 'https://en.wikipedia.org/wiki/Ford_EcoSport',
      officialUrl: 'https://www.india.ford.com/suvs/ecosport/',
      // status: 'Discontinued (2021)'
    },
    {
      id: 37,
      brand: 'Mazda',
      model: 'CX-3',
      price: 1620000,
      releaseDate: new Date(2015, 2, 15),
      bodyType: 'Compact SUV',
      engine: '2.0L Skyactiv-G',
      fuelType: 'Petrol',
      transmission: 'Manual / Automatic',
      color: 'Soul Red Crystal',
      imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/2/2d/2019_Mazda_CX-3_GT_AWD_front_6.16.19.jpg',
      wikiUrl: 'https://en.wikipedia.org/wiki/Mazda_CX-3',
      officialUrl: 'https://www.mazdausa.com/vehicles/cx-3',
      // status: 'Not Sold in India'
    },


    {
      id: 38,
      brand: 'BMW',
      model: '2 Series Gran Coupe',
      price: 4370000,
      releaseDate: new Date(2020, 9, 15),
      bodyType: 'Coupe',
      engine: '2.0L TwinPower Turbo',
      fuelType: 'Petrol / Diesel',
      transmission: 'Automatic (8-speed)',
      color: 'Misano Blue',
      imageUrl: 'https://imgd.aeplcdn.com/310x174/n/cw/ec/38679/2-series-gran-coupe-exterior-right-front-three-quarter.jpeg',
      wikiUrl: 'https://en.wikipedia.org/wiki/BMW_2_Series_(F44)',
      officialUrl: 'https://www.bmw.in/en/all-models/2-series/gran-coupe/2021/bmw-2-series-gran-coupe-overview.html'
    },
    {
      id: 39,
      brand: 'Mercedes-Benz',
      model: 'CLA',
      price: 4400000,
      releaseDate: new Date(2020, 0, 28),
      bodyType: 'Coupe',
      engine: '2.0L Turbocharged',
      fuelType: 'Petrol',
      transmission: '7-speed DCT',
      color: 'Polar White',
      imageUrl: 'https://imgd.aeplcdn.com/310x174/n/cw/ec/43591/cla-exterior-right-front-three-quarter.jpeg',
      wikiUrl: 'https://en.wikipedia.org/wiki/Mercedes-Benz_CLA-Class',
      officialUrl: 'https://www.mercedes-benz.co.in/passengercars/models/saloon/cla/overview.html'
    },
    {
      id: 40,
      brand: 'Audi',
      model: 'TT',
      price: 4000000,
      releaseDate: new Date(2015, 3, 23),
      bodyType: 'Coupe',
      engine: '2.0L TFSI',
      fuelType: 'Petrol',
      transmission: '6-speed S tronic',
      color: 'Vegas Yellow',
      imageUrl: 'https://imgd.aeplcdn.com/310x174/n/cw/ec/142195/tt-exterior-right-front-three-quarter-2.jpeg',
      wikiUrl: 'https://en.wikipedia.org/wiki/Audi_TT',
      officialUrl: 'https://www.audi.in/in/web/en/models/tt/tt-coupe.html',
      // status: 'Discontinued'
    },
    {
      id: 41,
      brand: 'Toyota',
      model: 'GR Supra',
      price: 12000000,
      releaseDate: new Date(2020, 0, 1),
      bodyType: 'Coupe',
      engine: '3.0L Twin-scroll Turbo',
      fuelType: 'Petrol',
      transmission: '8-speed Automatic',
      color: 'Renaissance Red',
      imageUrl: 'https://imgd.aeplcdn.com/310x174/n/cw/ec/43423/supra-exterior-right-front-three-quarter.jpeg',
      wikiUrl: 'https://en.wikipedia.org/wiki/Toyota_GR_Supra',
      officialUrl: 'https://www.toyota.com/grsupra/',
      // status: 'CBU, Not Sold in India'
    },



    {
      id: 42,
      brand: 'Mini',
      model: 'Cooper Convertible',
      price: 4800000,
      releaseDate: new Date(2021, 9, 1),
      bodyType: 'Convertible',
      engine: '2.0L TwinPower Turbo',
      fuelType: 'Petrol',
      transmission: '7-speed DCT',
      color: 'Zesty Yellow',
      imageUrl: 'https://imgd.aeplcdn.com/310x174/n/cw/ec/38881/cooper-convertible-exterior-right-front-three-quarter.jpeg',
      wikiUrl: 'https://en.wikipedia.org/wiki/Mini_Convertible',
      officialUrl: 'https://www.mini.in/en_IN/home/range/mini-convertible.html'
    },
    {
      id: 43,
      brand: 'Mercedes-Benz',
      model: 'E-Class Cabriolet',
      price: 9500000,
      releaseDate: new Date(2022, 3, 20),
      bodyType: 'Convertible',
      engine: '3.0L Inline-6 Turbo',
      fuelType: 'Petrol',
      transmission: '9-speed AT',
      color: 'Designo Hyacinth Red',
      imageUrl: 'https://imgd.aeplcdn.com/310x174/n/cw/ec/144445/e-class-cabriolet-exterior-right-front-three-quarter.jpeg',
      wikiUrl: 'https://en.wikipedia.org/wiki/Mercedes-Benz_E-Class_(W213)#Coupé_and_cabriolet_(C238/A238)',
      officialUrl: 'https://www.mercedes-benz.co.in/passengercars/models/cabriolet/e-class-cabriolet/overview.html'
    },
    {
      id: 44,
      brand: 'Volkswagen',
      model: 'Beetle Convertible',
      price: 2500000,
      releaseDate: new Date(2015, 0, 1),
      bodyType: 'Convertible',
      engine: '1.4L TSI',
      fuelType: 'Petrol',
      transmission: '7-speed DSG',
      color: 'Habanero Orange',
      imageUrl: 'https://imgd.aeplcdn.com/310x174/n/cw/ec/107513/beetle-convertible-exterior-right-front-three-quarter.jpeg',
      wikiUrl: 'https://en.wikipedia.org/wiki/Volkswagen_Beetle_(A5)',
      officialUrl: 'https://www.vw.com/en/models/beetle-convertible.html',

    },
    {
      id: 45,
      brand: 'Mazda',
      model: 'MX-5',
      price: 4500000,
      releaseDate: new Date(2020, 2, 1),
      bodyType: 'Convertible',
      engine: '2.0L SKYACTIV-G',
      fuelType: 'Petrol',
      transmission: '6-speed Manual / Automatic',
      color: 'Soul Red Crystal',
      imageUrl: 'https://imgd.aeplcdn.com/310x174/n/cw/ec/108317/mx5-exterior-right-front-three-quarter.jpeg',
      wikiUrl: 'https://en.wikipedia.org/wiki/Mazda_MX-5',
      officialUrl: 'https://www.mazda.com/en/innovation/mazda-stories/mx-5/',

    },
    {
      id: 46,
      brand: 'Fiat',
      model: 'Palio Weekend',
      price: 400000,
      releaseDate: new Date(2007, 0, 1),
      bodyType: 'Wagon/Estate',
      engine: '1.6L',
      fuelType: 'Petrol',
      transmission: '5-speed Manual',
      color: 'Metallic Green',
      imageUrl: 'https://imgd.aeplcdn.com/310x174/n/cw/ec/108469/palio-weekend-exterior-right-front-three-quarter.jpeg',
      wikiUrl: 'https://en.wikipedia.org/wiki/Fiat_Palio',
      officialUrl: 'Discontinued'
    },

    {
      id: 47,
      brand: 'Skoda',
      model: 'Octavia Combi',
      price: 1800000,
      releaseDate: new Date(2015, 0, 1),
      bodyType: 'Wagon/Estate',
      engine: '2.0L TDI',
      fuelType: 'Diesel',
      transmission: '6-speed Manual',
      color: 'Brilliant Silver',
      imageUrl: 'https://imgd.aeplcdn.com/310x174/n/cw/ec/108471/octavia-combi-exterior-right-front-three-quarter.jpeg',
      wikiUrl: 'https://en.wikipedia.org/wiki/Skoda_Octavia#Combi',
      officialUrl: 'Discontinued'
    },
    {
      id: 48,
      brand: 'Subaru',
      model: 'Outback',
      price: 4500000,
      releaseDate: new Date(2020, 1, 1),
      bodyType: 'Wagon/Estate',
      engine: '2.5L Boxer Engine',
      fuelType: 'Petrol',
      transmission: 'CVT',
      color: 'Crystal White Pearl',
      imageUrl: 'https://imgd.aeplcdn.com/310x174/n/cw/ec/108470/outback-exterior-right-front-three-quarter.jpeg',
      wikiUrl: 'https://en.wikipedia.org/wiki/Subaru_Outback',
      officialUrl: 'Not Sold in India'
    },



    {
      id: 49,
      brand: 'Maruti Suzuki',
      model: 'S-Cross',
      price: 900000,
      releaseDate: new Date(2022, 0, 1),
      bodyType: 'Crossover',
      engine: '1.5L Petrol',
      fuelType: 'Petrol',
      transmission: '5-speed Manual',
      color: 'Nexa Blue',
      imageUrl: 'https://imgd.aeplcdn.com/310x174/n/cw/ec/108472/s-cross-exterior-right-front-three-quarter.jpeg',
      wikiUrl: 'https://en.wikipedia.org/wiki/Maruti_S-Cross',
      officialUrl: 'https://www.nexaexperience.com/s-cross',
      // status: 'Discontinued'
    },
    {
      id: 50,
      brand: 'Renault',
      model: 'Kiger',
      price: 650000,
      releaseDate: new Date(2021, 1, 1),
      bodyType: 'Crossover',
      engine: '1.0L Turbo Petrol',
      fuelType: 'Petrol',
      transmission: '5-speed Manual',
      color: 'Planet Grey',
      imageUrl: 'https://imgd.aeplcdn.com/310x174/n/cw/ec/108473/kiger-exterior-right-front-three-quarter.jpeg',
      wikiUrl: 'https://en.wikipedia.org/wiki/Renault_Kiger',
      officialUrl: 'https://www.renault.co.in/cars/kiger.html',
      // status: 'Available'
    },
    {
      id: 51,
      brand: 'Honda',
      model: 'WR-V',
      price: 870000,
      releaseDate: new Date(2020, 0, 1),
      bodyType: 'Crossover',
      engine: '1.2L Petrol',
      fuelType: 'Petrol',
      transmission: '5-speed Manual',
      color: 'Golden Brown',
      imageUrl: 'https://imgd.aeplcdn.com/310x174/n/cw/ec/108474/wr-v-exterior-right-front-three-quarter.jpeg',
      wikiUrl: 'https://en.wikipedia.org/wiki/Honda_WR-V',
      officialUrl: 'https://www.hondacarindia.com/honda-wrv',
      // status: 'Discontinued'
    },
    {
      id: 52,
      brand: 'Nissan',
      model: 'Juke',
      price: 1200000,
      releaseDate: new Date(2019, 0, 1),
      bodyType: 'Crossover',
      engine: '1.6L Petrol',
      fuelType: 'Petrol',
      transmission: '6-speed Manual',
      color: 'Flame Red',
      imageUrl: 'https://imgd.aeplcdn.com/310x174/n/cw/ec/108475/juke-exterior-right-front-three-quarter.jpeg',
      wikiUrl: 'https://en.wikipedia.org/wiki/Nissan_Juke',
      officialUrl: 'https://www.nissan.co.uk/vehicles/new-vehicles/juke.html',
      // status: 'Not Sold in India'
    },
    {
      id: 53,
      brand: 'Toyota',
      model: 'Innova Hycross',
      price: 1850000,
      releaseDate: new Date(2023, 0, 1),
      bodyType: 'MPV',
      engine: '2.0L Petrol',
      fuelType: 'Petrol',
      transmission: 'CVT',
      color: 'Pearl White',
      imageUrl: 'https://imgd.aeplcdn.com/310x174/n/cw/ec/108476/innova-hycross-exterior-right-front-three-quarter.jpeg',
      wikiUrl: 'https://en.wikipedia.org/wiki/Toyota_Innova',
      officialUrl: 'https://www.toyotabharat.com/showroom/innovahycross/',
      // status: 'Available'
    },
    {
      id: 54,
      brand: 'Maruti Suzuki',
      model: 'Ertiga/XL6',
      price: 1150000,
      releaseDate: new Date(2018, 0, 1),
      bodyType: 'MPV',
      engine: '1.5L Petrol',
      fuelType: 'Petrol',
      transmission: '5-speed Manual',
      color: 'Auburn Red',
      imageUrl: 'https://imgd.aeplcdn.com/310x174/n/cw/ec/108477/ertiga-xl6-exterior-right-front-three-quarter.jpeg',
      wikiUrl: 'https://en.wikipedia.org/wiki/Maruti_Suzuki_Ertiga',
      officialUrl: 'https://www.nexaexperience.com/xl6',
      // status: 'Available'
    },
    {
      id: 55,
      brand: 'Kia',
      model: 'Carens',
      price: 1100000,
      releaseDate: new Date(2022, 0, 1),
      bodyType: 'MPV',
      engine: '1.4L Turbo Petrol',
      fuelType: 'Petrol',
      transmission: '6-speed Manual',
      color: 'Intense Red',
      imageUrl: 'https://imgd.aeplcdn.com/310x174/n/cw/ec/108478/carens-exterior-right-front-three-quarter.jpeg',
      wikiUrl: 'https://en.wikipedia.org/wiki/Kia_Carens',
      officialUrl: 'https://www.kia.com/in/carens.html',
      // status: 'Available'
    },
    {
      id: 56,
      brand: 'Mahindra',
      model: 'Marazzo',
      price: 1300000,
      releaseDate: new Date(2018, 0, 1),
      bodyType: 'MPV',
      engine: '1.5L Diesel',
      fuelType: 'Diesel',
      transmission: '6-speed Manual',
      color: 'Shimmering Silver',
      imageUrl: 'https://imgd.aeplcdn.com/310x174/n/cw/ec/108479/marazzo-exterior-right-front-three-quarter.jpeg',
      wikiUrl: 'https://en.wikipedia.org/wiki/Mahindra_Marazzo',
      officialUrl: 'https://auto.mahindra.com/suv/marazzo',
      // status: 'Available'
    },
    {
      id: 57,
      brand: 'Chevrolet',
      model: 'Enjoy',
      price: 850000,
      releaseDate: new Date(2011, 0, 1),
      bodyType: 'MPV',
      engine: '1.3L Diesel',
      fuelType: 'Diesel',
      transmission: '5-speed Manual',
      color: 'Summit White',
      imageUrl: 'https://imgd.aeplcdn.com/310x174/n/cw/ec/108480/enjoy-exterior-right-front-three-quarter.jpeg',
      wikiUrl: 'https://en.wikipedia.org/wiki/Chevrolet_Enjoy',
      officialUrl: 'https://www.chevrolet.co.in/owners-area.html',
      // status: 'Discontinued'
    },
    {
      id: 58,
      brand: 'Honda',
      model: 'Odyssey',
      price: 3200000,
      releaseDate: new Date(2003, 0, 1),
      bodyType: 'MPV',
      engine: '2.4L Petrol',
      fuelType: 'Petrol',
      transmission: '5-speed Automatic',
      color: 'Taffeta White',
      imageUrl: 'https://imgd.aeplcdn.com/310x174/n/cw/ec/108481/odyssey-exterior-right-front-three-quarter.jpeg',
      wikiUrl: 'https://en.wikipedia.org/wiki/Honda_Odyssey',
      officialUrl: 'https://automobiles.honda.com/odyssey',
      // status: 'Not Sold in India'
    },



    {
      id: 59,
      brand: 'BMW',
      model: 'Z4',
      price: 6500000,
      releaseDate: new Date(2019, 0, 1),
      bodyType: 'Roadster',
      engine: '2.0L Turbo Petrol',
      fuelType: 'Petrol',
      transmission: '8-speed Automatic',
      color: 'Sophisto Grey',
      imageUrl: 'https://imgd.aeplcdn.com/310x174/n/cw/ec/108482/z4-exterior-right-front-three-quarter.jpeg',
      wikiUrl: 'https://en.wikipedia.org/wiki/BMW_Z4',
      officialUrl: 'Available'
    },
    {
      id: 60,
      brand: 'Porsche',
      model: '718 Boxster',
      price: 7600000,
      releaseDate: new Date(2016, 0, 1),
      bodyType: 'Roadster',
      engine: '2.0L Turbo Petrol',
      fuelType: 'Petrol',
      transmission: '6-speed Manual',
      color: 'Carrara White',
      imageUrl: 'https://imgd.aeplcdn.com/310x174/n/cw/ec/108483/718-boxster-exterior-right-front-three-quarter.jpeg',
      wikiUrl: 'https://en.wikipedia.org/wiki/Porsche_718',
      officialUrl: 'Available'
    },
    {
      id: 61,
      brand: 'Mercedes-Benz',
      model: 'SLK',
      price: 7500000,
      releaseDate: new Date(1996, 0, 1),
      bodyType: 'Roadster',
      engine: '1.8L Petrol',
      fuelType: 'Petrol',
      transmission: '5-speed Automatic',
      color: 'Iridium Silver',
      imageUrl: 'https://imgd.aeplcdn.com/310x174/n/cw/ec/108484/slk-exterior-right-front-three-quarter.jpeg',
      wikiUrl: 'https://en.wikipedia.org/wiki/Mercedes-Benz_SLK-Class',
      officialUrl: 'Discontinued'
    },
    {
      id: 62,
      brand: 'Porsche',
      model: '911',
      price: 10500000,
      releaseDate: new Date(1964, 0, 1),
      bodyType: 'Sports Car',
      engine: '3.0L Twin-Turbo Flat-Six',
      fuelType: 'Petrol',
      transmission: '7-speed PDK Automatic',
      color: 'Carrara White',
      imageUrl: 'https://imgd.aeplcdn.com/310x174/n/cw/ec/108485/911-exterior-right-front-three-quarter.jpeg',
      wikiUrl: 'https://en.wikipedia.org/wiki/Porsche_911',
      officialUrl: 'Available'
    },
    {
      id: 63,
      brand: 'Nissan',
      model: 'GT-R',
      price: 9500000,
      releaseDate: new Date(2007, 0, 1),
      bodyType: 'Sports Car',
      engine: '3.8L Twin-Turbo V6',
      fuelType: 'Petrol',
      transmission: '6-speed Manual',
      color: 'Jet Black',
      imageUrl: 'https://imgd.aeplcdn.com/310x174/n/cw/ec/108486/gt-r-exterior-right-front-three-quarter.jpeg',
      wikiUrl: 'https://en.wikipedia.org/wiki/Nissan_GT-R',
      officialUrl: 'Available'
    },
    {
      id: 64,
      brand: 'Audi',
      model: 'R8',
      price: 18000000,
      releaseDate: new Date(2006, 0, 1),
      bodyType: 'Sports Car',
      engine: '5.2L V10',
      fuelType: 'Petrol',
      transmission: '7-speed S-Tronic Automatic',
      color: 'Daytona Gray',
      imageUrl: 'https://imgd.aeplcdn.com/310x174/n/cw/ec/108487/r8-exterior-right-front-three-quarter.jpeg',
      wikiUrl: 'https://en.wikipedia.org/wiki/Audi_R8',
      officialUrl: 'Available (limited stock)'
    },
    {
      id: 65,
      brand: 'Mercedes-Benz',
      model: 'AMG GT',
      price: 12000000,
      releaseDate: new Date(2015, 0, 1),
      bodyType: 'Sports Car',
      engine: '4.0L Twin-Turbo V8',
      fuelType: 'Petrol',
      transmission: '7-speed Dual Clutch Automatic',
      color: 'Iridium Silver',
      imageUrl: 'https://imgd.aeplcdn.com/310x174/n/cw/ec/108488/amg-gt-exterior-right-front-three-quarter.jpeg',
      wikiUrl: 'https://en.wikipedia.org/wiki/Mercedes-AMG_GT',
      officialUrl: 'Available'
    },
    {
      id: 66,
      brand: 'Ford',
      model: 'Mustang',
      price: 6500000,
      releaseDate: new Date(1964, 0, 1),
      bodyType: 'Sports Car',
      engine: '5.0L V8',
      fuelType: 'Petrol',
      transmission: '6-speed Manual',
      color: 'Race Red',
      imageUrl: 'https://imgd.aeplcdn.com/310x174/n/cw/ec/108489/mustang-exterior-right-front-three-quarter.jpeg',
      wikiUrl: 'https://en.wikipedia.org/wiki/Ford_Mustang',
      officialUrl: 'Discontinued'
    },
    {
      id: 67,
      brand: 'Chevrolet',
      model: 'Corvette',
      price: 8500000,
      releaseDate: new Date(1953, 0, 1),
      bodyType: 'Sports Car',
      engine: '6.2L V8',
      fuelType: 'Petrol',
      transmission: '8-speed Dual Clutch Automatic',
      color: 'Torch Red',
      imageUrl: 'https://imgd.aeplcdn.com/310x174/n/cw/ec/108490/corvette-exterior-right-front-three-quarter.jpeg',
      wikiUrl: 'https://en.wikipedia.org/wiki/Chevrolet_Corvette',
      officialUrl: 'Discontinued (C8 expected via CBU)'
    },
    {
      id: 68,
      brand: 'Mercedes-Benz',
      model: 'S-Class',
      price: 15000000,
      releaseDate: new Date(1954, 0, 1),
      bodyType: 'Luxury Car',
      engine: '3.0L Inline-6 Turbo',
      fuelType: 'Petrol',
      transmission: '9-speed AT',
      color: 'Obsidian Black',
      imageUrl: 'https://imgd.aeplcdn.com/310x174/n/cw/ec/108491/s-class-exterior-right-front-three-quarter.jpeg',
      wikiUrl: 'https://en.wikipedia.org/wiki/Mercedes-Benz_S-Class',
      officialUrl: 'Available'
    },
    {
      id: 69,
      brand: 'BMW',
      model: '7 Series',
      price: 17000000,
      releaseDate: new Date(1977, 0, 1),
      bodyType: 'Luxury Car',
      engine: '3.0L Inline-6 Turbo',
      fuelType: 'Petrol',
      transmission: '8-speed Automatic',
      color: 'Alpine White',
      imageUrl: 'https://imgd.aeplcdn.com/310x174/n/cw/ec/108492/7-series-exterior-right-front-three-quarter.jpeg',
      wikiUrl: 'https://en.wikipedia.org/wiki/BMW_7_Series',
      officialUrl: 'Available'
    },
    {
      id: 70,
      brand: 'Audi',
      model: 'A8',
      price: 9000000,
      releaseDate: new Date(1994, 0, 1),
      bodyType: 'Luxury Car',
      engine: '3.0L V6 Turbo',
      fuelType: 'Petrol',
      transmission: '8-speed Automatic',
      color: 'Floret Silver',
      imageUrl: 'https://imgd.aeplcdn.com/310x174/n/cw/ec/108493/a8-exterior-right-front-three-quarter.jpeg',
      wikiUrl: 'https://en.wikipedia.org/wiki/Audi_A8',
      officialUrl: 'Available'
    },
    {
      id: 71,
      brand: 'Lexus',
      model: 'LS',
      price: 12500000,
      releaseDate: new Date(1989, 0, 1),
      bodyType: 'Luxury Car',
      engine: '3.5L V6 Hybrid',
      fuelType: 'Hybrid',
      transmission: '10-speed Automatic',
      color: 'Manganese Luster',
      imageUrl: 'https://imgd.aeplcdn.com/310x174/n/cw/ec/108494/ls-exterior-right-front-three-quarter.jpeg',
      wikiUrl: 'https://en.wikipedia.org/wiki/Lexus_LS',
      officialUrl: 'Available (limited units)'
    },
    {
      id: 72,
      brand: 'Jaguar',
      model: 'XJ',
      price: 10500000,
      releaseDate: new Date(1968, 0, 1),
      bodyType: 'Luxury Car',
      engine: '3.0L V6 Supercharged',
      fuelType: 'Petrol',
      transmission: '8-speed Automatic',
      color: 'Ultimate Black',
      imageUrl: 'https://imgd.aeplcdn.com/310x174/n/cw/ec/108495/xj-exterior-right-front-three-quarter.jpeg',
      wikiUrl: 'https://en.wikipedia.org/wiki/Jaguar_XJ',
      officialUrl: 'Discontinued'
    },
    {
      id: 73,
      brand: 'BMW',
      model: 'X7',
      price: 12000000,
      releaseDate: new Date(2018, 0, 1),
      bodyType: 'Luxury SUV',
      engine: '3.0L Inline-6 Turbo',
      fuelType: 'Petrol',
      transmission: '8-speed Automatic',
      color: 'Arctic Grey',
      imageUrl: 'https://imgd.aeplcdn.com/310x174/n/cw/ec/108496/x7-exterior-right-front-three-quarter.jpeg',
      wikiUrl: 'https://en.wikipedia.org/wiki/BMW_X7',
      officialUrl: 'Available'
    },
    {
      id: 74,
      brand: 'Range Rover',
      model: 'Velar',
      price: 9500000,
      releaseDate: new Date(2017, 0, 1),
      bodyType: 'Luxury SUV',
      engine: '2.0L Turbocharged Petrol',
      fuelType: 'Petrol',
      transmission: '8-speed Automatic',
      color: 'Portofino Blue',
      imageUrl: 'https://imgd.aeplcdn.com/310x174/n/cw/ec/108497/velar-exterior-right-front-three-quarter.jpeg',
      wikiUrl: 'https://en.wikipedia.org/wiki/Range_Rover_Velar',
      officialUrl: 'Available'
    },
    {
      id: 75,
      brand: 'Audi',
      model: 'Q7',
      price: 10500000,
      releaseDate: new Date(2005, 0, 1),
      bodyType: 'Luxury SUV',
      engine: '3.0L V6 Turbocharged Petrol',
      fuelType: 'Petrol',
      transmission: '8-speed Automatic',
      color: 'Moonlight Blue',
      imageUrl: 'https://imgd.aeplcdn.com/310x174/n/cw/ec/108498/q7-exterior-right-front-three-quarter.jpeg',
      wikiUrl: 'https://en.wikipedia.org/wiki/Audi_Q7',
      officialUrl: 'Available'
    },
      {
        id: 76,
        brand: 'Nissan',
        model: 'Evalia',
        price: 1200000, // Approximate price
        releaseDate: new Date(2012, 8, 1),
        bodyType: 'Premium MPV',
        engine: '1.5L Diesel',
        fuelType: 'Diesel',
        transmission: '5-speed Manual',
        color: 'Blade Silver',
        imageUrl: 'https://imgd.aeplcdn.com/310x174/n/cw/ec/108499/evalia-exterior-right-front-three-quarter.jpeg',
        wikiUrl: 'https://en.wikipedia.org/wiki/Nissan_NV200#India',
        officialUrl: 'https://www.nissan.in/vehicles/pv/evalia.html'
      },
      {
        id: 77,
        brand: 'Tata',
        model: 'Nexon EV',
        price: 1499000, // Approximate price
        releaseDate: new Date(2020, 0, 28),
        bodyType: 'Electric SUV',
        engine: 'Permanent Magnet Synchronous Motor',
        fuelType: 'Electric',
        transmission: 'Automatic',
        color: 'Signature Teal Blue',
        imageUrl: 'https://imgd.aeplcdn.com/310x174/n/cw/ec/44745/nexon-ev-right-front-three-quarter.jpeg',
        wikiUrl: 'https://en.wikipedia.org/wiki/Tata_Nexon#Electric_Variant_(Nexon_EV)',
        officialUrl: 'https://www.tatamotors.com/vehicles/nexon-ev/'
      },
      {
        id: 78,
        brand: 'MG',
        model: 'ZS EV',
        price: 2299000, // Approximate price
        releaseDate: new Date(2020, 0, 23),
        bodyType: 'Electric SUV',
        engine: 'Permanent Magnet Synchronous Motor',
        fuelType: 'Electric',
        transmission: 'Automatic',
        color: 'Ferris White',
        imageUrl: 'https://imgd.aeplcdn.com/310x174/n/cw/ec/132559/zs-ev-exterior-right-front-three-quarter.jpeg',
        wikiUrl: 'https://en.wikipedia.org/wiki/MG_ZS_EV',
        officialUrl: 'https://www.mgmotor.co.in/zs-ev'
      },
      {
        id: 79,
        brand: 'Hyundai',
        model: 'Kona Electric',
        price: 2399000, // Approximate price
        releaseDate: new Date(2019, 6, 9),
        bodyType: 'Electric SUV',
        engine: 'Permanent Magnet Synchronous Motor',
        fuelType: 'Electric',
        transmission: 'Automatic',
        color: 'Polar White with Phantom Black Roof',
        imageUrl: 'https://imgd.aeplcdn.com/310x174/n/cw/ec/41107/kona-electric-right-front-three-quarter.jpeg',
        wikiUrl: 'https://en.wikipedia.org/wiki/Hyundai_Kona#Electric_version',
        officialUrl: 'https://www.hyundai.com/in/en/find-a-car/konacross/konacross-electric'
      },
      {
        id: 80,
        brand: 'BMW',
        model: 'i4',
        price: 7499000, // Approximate price
        releaseDate: new Date(2022, 4, 26),
        bodyType: 'Electric Sedan',
        engine: 'Fifth-generation BMW eDrive',
        fuelType: 'Electric',
        transmission: 'Automatic',
        color: 'Mineral White Metallic',
        imageUrl: 'https://imgd.aeplcdn.com/310x174/n/cw/ec/118819/i4-exterior-right-front-three-quarter.jpeg',
        wikiUrl: 'https://en.wikipedia.org/wiki/BMW_i4',
        officialUrl: 'https://www.bmw.in/en/all-models/i/i4/2022/bmw-i4-in-brief.html'
      },
      {
        id: 81,
        brand: 'BMW',
        model: 'i7',
        price: 15990000, // Approximate price
        releaseDate: new Date(2023, 0, 7),
        bodyType: 'Luxury Electric Sedan',
        engine: 'Dual Electric Motors',
        fuelType: 'Electric',
        transmission: 'Automatic',
        color: 'Oxide Grey Metallic',
        imageUrl: 'https://imgd.aeplcdn.com/310x174/n/cw/ec/125385/i7-exterior-right-front-three-quarter.jpeg',
        wikiUrl: 'https://en.wikipedia.org/wiki/BMW_7_Series_(G70)',
        officialUrl: 'https://www.bmw.in/en/all-models/7-series/7-series.html'
      },
      {
        id: 82,
        brand: 'Mercedes-Benz',
        model: 'EQC',
        price: 9999000, // Approximate price
        releaseDate: new Date(2020, 9, 8),
        bodyType: 'Luxury Electric SUV',
        engine: 'Dual asynchronous electric motors',
        fuelType: 'Electric',
        transmission: 'Automatic',
        color: 'High-Tech Silver',
        imageUrl: 'https://imgd.aeplcdn.com/310x174/n/cw/ec/41849/eqc-exterior-right-front-three-quarter.jpeg',
        wikiUrl: 'https://en.wikipedia.org/wiki/Mercedes-Benz_EQC',
        officialUrl: 'https://www.mercedes-benz.co.in/passenger-cars/models/eqc.html'
      },
      {
        id: 83,
        brand: 'BYD',
        model: 'Atto 3',
        price: 2999000, // Approximate price
        releaseDate: new Date(2022, 9, 11),
        bodyType: 'Electric SUV',
        engine: 'Permanent Magnet Synchronous Motor',
        fuelType: 'Electric',
        transmission: 'Automatic',
        color: 'Surf Blue',
        imageUrl: 'https://imgd.aeplcdn.com/310x174/n/cw/ec/124533/atto-3-exterior-right-front-three-quarter.jpeg',
        wikiUrl: 'https://en.wikipedia.org/wiki/BYD_Atto_3',
        officialUrl: 'https://www.byd.com/in/'
      },
      {
        id: 84,
        brand: 'Hyundai',
        model: 'Ioniq 5',
        price: 3599000, // Approximate price
        releaseDate: new Date(2023, 0, 11),
        bodyType: 'Electric Crossover',
        engine: 'Electric Motor with 72.6 kWh Battery',
        fuelType: 'Electric',
        transmission: 'Automatic',
        color: 'Gravity Gold Matte',
        imageUrl: 'https://imgd.aeplcdn.com/310x174/n/cw/ec/139759/ioniq-5-exterior-right-front-three-quarter.jpeg',
        wikiUrl: 'https://en.wikipedia.org/wiki/Hyundai_Ioniq_5',
        officialUrl: 'https://www.hyundai.com/in/en/find-a-car/ioniq5/ioniq5'
      },
      {
        id: 85,
        brand: 'Citroen',
        model: 'eC3',
        price: 899000, // Approximate price
        releaseDate: new Date(2023, 1, 27),
        bodyType: 'Electric Hatchback',
        engine: 'Permanent Magnet Synchronous Motor',
        fuelType: 'Electric',
        transmission: 'Automatic',
        color: 'Zesty Orange',
        imageUrl: 'https://imgd.aeplcdn.com/310x174/n/cw/ec/139509/ec3-exterior-right-front-three-quarter.jpeg',
        wikiUrl: 'https://en.wikipedia.org/wiki/Citro%C3%ABn_C3_(CC21)',
        officialUrl: 'https://www.citroen.in/'
      }





  ];



  getProducts(): Product[] {
    return this.products;
  }
}
