import { Injectable } from '@angular/core';
import { Product } from '../models/product.model';
//import { Product } from '../models/product.model';


@Injectable({
  providedIn: 'root',
})
export class ProductService {
  private products: Product[] = [

      {
        id: 1,
        brand: 'BMW',
        model: 'X5',
        price: 75000,
        releaseDate: new Date(2023, 4, 12),
        bodyType: 'SUV',
        engine: '3.0L Turbo Inline-6',
        fuelType: 'Petrol',
        transmission: 'Automatic',
        color: 'Black',
        imageUrl: '/car1.webp',
      },
      {
        id: 2,
        brand: 'Mercedes-Benz',
        model: 'C-Class',
        price: 65000,
        releaseDate: new Date(2022, 10, 20),
        bodyType: 'Sedan',
        engine: '2.0L Turbo',
        fuelType: 'Diesel',
        transmission: 'Automatic',
        color: 'White',
        imageUrl: '/car2.webp',
      },
      {
        id: 3,
        brand: 'Tata',
        model: 'Nexon EV',
        price: 19000,
        releaseDate: new Date(2023, 7, 1),
        bodyType: 'SUV',
        engine: 'Electric Motor',
        fuelType: 'Electric',
        transmission: 'Automatic',
        color: 'Blue',
        imageUrl: '/car3.webp',
      },
      {
        id: 4,
        brand: 'Hyundai',
        model: 'i20',
        price: 10000,
        releaseDate: new Date(2023, 1, 18),
        bodyType: 'Hatchback',
        engine: '1.2L Petrol',
        fuelType: 'Petrol',
        transmission: 'Manual',
        color: 'Red',
        imageUrl: '/car4.webp',
      },
      {
        id: 5,
        brand: 'Maruti Suzuki',
        model: 'Baleno',
        price: 9500,
        releaseDate: new Date(2022, 3, 15),
        bodyType: 'Hatchback',
        engine: '1.2L VVT',
        fuelType: 'Petrol',
        transmission: 'Manual',
        color: 'Grey',
        imageUrl: '/car5.webp',
      },
      {
        id: 6,
        brand: 'Audi',
        model: 'A4',
        price: 55000,
        releaseDate: new Date(2023, 2, 28),
        bodyType: 'Sedan',
        engine: '2.0L TFSI',
        fuelType: 'Petrol',
        transmission: 'Automatic',
        color: 'Silver',
        imageUrl: '/car1.webp',
      },
      {
        id: 7,
        brand: 'Kia',
        model: 'Seltos',
        price: 17000,
        releaseDate: new Date(2022, 11, 5),
        bodyType: 'SUV',
        engine: '1.5L CRDi',
        fuelType: 'Diesel',
        transmission: 'Manual',
        color: 'Blue',
        imageUrl: '/car2.webp',
      },
      {
        id: 8,
        brand: 'Volkswagen',
        model: 'Virtus',
        price: 16000,
        releaseDate: new Date(2023, 5, 25),
        bodyType: 'Sedan',
        engine: '1.0L TSI',
        fuelType: 'Petrol',
        transmission: 'Manual',
        color: 'Red',
        imageUrl: '/car3.webp',
      },
      {
        id: 9,
        brand: 'Mahindra',
        model: 'XUV700',
        price: 22000,
        releaseDate: new Date(2023, 3, 10),
        bodyType: 'SUV',
        engine: '2.2L mHawk Diesel',
        fuelType: 'Diesel',
        transmission: 'Automatic',
        color: 'Black',
        imageUrl: '/car4.webp',
      },
      {
        id: 10,
        brand: 'Honda',
        model: 'City',
        price: 15000,
        releaseDate: new Date(2023, 6, 8),
        bodyType: 'Sedan',
        engine: '1.5L i-VTEC',
        fuelType: 'Petrol',
        transmission: 'Manual',
        color: 'White',
        imageUrl: '/car4.webp',
      },
      {
        id: 11,
        brand: 'Skoda',
        model: 'Kushaq',
        price: 18000,
        releaseDate: new Date(2022, 7, 14),
        bodyType: 'SUV',
        engine: '1.0L TSI',
        fuelType: 'Petrol',
        transmission: 'Manual',
        color: 'Orange',
        imageUrl: '/car4.webp',
      },
      {
        id: 12,
        brand: 'MG',
        model: 'Hector',
        price: 20000,
        releaseDate: new Date(2023, 8, 19),
        bodyType: 'SUV',
        engine: '1.5L Turbo Petrol',
        fuelType: 'Petrol',
        transmission: 'Automatic',
        color: 'Grey',
        imageUrl: '/car5.webp',
      },
      {
        id: 13,
        brand: 'Toyota',
        model: 'Innova HyCross',
        price: 30000,
        releaseDate: new Date(2023, 9, 22),
        bodyType: 'SUV',
        engine: '2.0L Hybrid',
        fuelType: 'Hybrid',
        transmission: 'Automatic',
        color: 'Silver',
        imageUrl: '/car5.webp',
      },
      {
        id: 14,
        brand: 'Ford',
        model: 'EcoSport',
        price: 16000,
        releaseDate: new Date(2021, 11, 4),
        bodyType: 'SUV',
        engine: '1.5L Petrol',
        fuelType: 'Petrol',
        transmission: 'Manual',
        color: 'Blue',
        imageUrl: '/car4.webp',
      },
      {
        id: 15,
        brand: 'Nissan',
        model: 'Magnite',
        price: 13000,
        releaseDate: new Date(2022, 10, 30),
        bodyType: 'SUV',
        engine: '1.0L Turbo',
        fuelType: 'Petrol',
        transmission: 'Manual',
        color: 'White',
        imageUrl: '/car4.webp',
      },
      {
        id: 16,
        brand: 'Renault',
        model: 'Kiger',
        price: 12000,
        releaseDate: new Date(2023, 1, 5),
        bodyType: 'SUV',
        engine: '1.0L Turbo',
        fuelType: 'Petrol',
        transmission: 'Manual',
        color: 'Silver',
        imageUrl: '/car4.webp',
      },
      {
        id: 17,
        brand: 'Tesla',
        model: 'Model 3',
        price: 48000,
        releaseDate: new Date(2023, 2, 11),
        bodyType: 'Sedan',
        engine: 'Dual Motor Electric',
        fuelType: 'Electric',
        transmission: 'Automatic',
        color: 'White',
        imageUrl: '/car4.webp',
      },
      {
        id: 18,
        brand: 'Jeep',
        model: 'Compass',
        price: 28000,
        releaseDate: new Date(2023, 3, 7),
        bodyType: 'SUV',
        engine: '2.0L Diesel',
        fuelType: 'Diesel',
        transmission: 'Manual',
        color: 'Red',
        imageUrl: '/car5.webp',
      },
      {
        id: 19,
        brand: 'Maruti Suzuki',
        model: 'Swift',
        price: 9000,
        releaseDate: new Date(2023, 4, 16),
        bodyType: 'Hatchback',
        engine: '1.2L DualJet',
        fuelType: 'Petrol',
        transmission: 'Manual',
        color: 'Grey',
        imageUrl: '/car5.webp',
      },
      {
        id: 20,
        brand: 'Honda',
        model: 'Amaze',
        price: 12000,
        releaseDate: new Date(2022, 12, 12),
        bodyType: 'Sedan',
        engine: '1.2L i-VTEC',
        fuelType: 'Petrol',
        transmission: 'Automatic',
        color: 'Black',
        imageUrl: '/car4.webp',
      }
    ];


  getProducts(): Product[] {
    return this.products;
  }
}
